# Generated by Django 2.2.5 on 2021-12-19 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_student_photo'),
        ('teacher', '0002_teacher_photo'),
    ]

    operations = [

        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('intro', models.CharField(default='精品书法课程', max_length=200)),
                ('admission_time', models.DateField(auto_now_add=True)),
                ('photo', models.ImageField(default='#', upload_to='')),
                ('fcourse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fcrouse', to='course.Course')),
            ],
            options={
                'db_table': 'course',
            },
        ),

        
    ]
