# Generated by Django 2.2.5 on 2021-12-22 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20211222_1321'),
        ('student', '0003_auto_20211222_2243'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('classroom_id', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('sec_id', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('choosed', models.IntegerField(default='0', verbose_name='已选人数')),
                ('capacity', models.IntegerField(default='30', verbose_name='课容量')),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Course', to='course.Course')),
                ('classroom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classroom', to='course.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='time_slot',
            fields=[
                ('time_slot_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('day', models.CharField(choices=[(1, '周一'), (2, '周二'), (3, '周三'), (4, '周四'), (5, '周五'), (6, '周六'), (7, '周日')], max_length=5)),
                ('start', models.DateField()),
                ('end', models.DateField()),
            ],
        ),

        migrations.AddField(
            model_name='section',
            name='time_slot',
            field=models.ManyToManyField(related_name='time_slot', to='course.time_slot'),
        ),
    ]
