# Generated by Django 2.2.5 on 2021-12-22 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20211223_0003'),
    ]

    operations = [

    ]
