# Generated by Django 2.2.5 on 2021-12-23 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_auto_20211223_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time_slot',
            name='end',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='time_slot',
            name='start',
            field=models.DateTimeField(),
        ),
    ]
