# Generated by Django 2.2.5 on 2021-12-23 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20211222_1321'),
        ('student', '0003_auto_20211222_2243'),
        ('course', '0004_auto_20211223_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='teach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ing', '上课中'), ('todo', '待开课'), ('ed', '上课中')], max_length=10)),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Teacher', to='teacher.Teacher')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_t', to='course.section')),
            ],
        ),
        migrations.CreateModel(
            name='take',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ing', '上课中'), ('todo', '待开课'), ('ed', '上课中')], max_length=10)),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Student', to='student.Student')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_s', to='course.section')),
            ],
        ),
    ]
