# Generated by Django 2.2.5 on 2021-12-23 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_take_teach'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='choosed_sum',
            field=models.IntegerField(default=0),
        ),
    ]
