# Generated by Django 2.2.5 on 2021-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_course_choosed_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='photo',
            field=models.ImageField(default='http://127.0.0.1:8000/upload/default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='section',
            name='capacity',
            field=models.IntegerField(default='50', verbose_name='课容量'),
        ),
    ]
