# Generated by Django 2.2.5 on 2021-12-23 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_auto_20211224_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='fcourse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_self', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='Course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section_self', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='section',
            name='classroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_self', to='course.classroom'),
        ),
        migrations.AlterField(
            model_name='take',
            name='Student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_self', to='student.Student'),
        ),
        migrations.AlterField(
            model_name='take',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='take_self', to='course.section'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='Teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach_self', to='teacher.Teacher'),
        ),
        migrations.AlterField(
            model_name='teach',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teach_self', to='course.section'),
        ),
    ]
