# Generated by Django 2.2.5 on 2021-12-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='male', max_length=5)),
                ('admission_time', models.DateField(auto_now_add=True)),
                ('intro', models.CharField(default='书法爱好者一名~', max_length=200)),
            ],
            options={
                'db_table': 'student',
            },
        ),
        migrations.CreateModel(
            name='StudentUsers',
            fields=[
                ('sid', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('s_username', models.CharField(max_length=10)),
                ('s_password', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'student_users',
            },
        ),
    ]
