# Generated by Django 2.2.5 on 2021-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20211222_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='defalut_avatar_1.jpg', upload_to=''),
        ),
    ]
