# Generated by Django 2.2.5 on 2021-12-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20211224_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(default='http://127.0.0.1:8000/upload/defalut_avatar_1.jpg', upload_to=''),
        ),
    ]
