# Generated by Django 2.2.5 on 2021-12-22 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='be_good_at',
            field=models.CharField(blank=True, choices=[('1', '楷书'), ('2', '行书')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='sex',
            field=models.CharField(blank=True, choices=[('1', '男'), ('2', '女')], max_length=5, null=True),
        ),
    ]
