# Generated by Django 2.2.5 on 2021-12-23 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20211222_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='photo',
            field=models.ImageField(default='http://127.0.0.1:8000/upload/teacher_default.jpg', upload_to=''),
        ),
    ]
