# Generated by Django 2.2.5 on 2021-12-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='uid',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='roles',
            field=models.CharField(choices=[('1', '学生'), ('2', '教师'), ('3', '管理员')], default='1', max_length=10, verbose_name='角色'),
        ),
    ]
