# Generated by Django 2.2.5 on 2021-12-27 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211222_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.CharField(blank=True, default='http://127.0.0.1:8000/upload/default_superadmin1.png', max_length=100, null=True, verbose_name='头像'),
        ),
    ]
